from __future__ import annotations
from typing import Protocol

class IndexNotReadyError(RuntimeError): pass

class BotServices(Protocol):
    cache: object
    def model(self) -> str: ...
    def set_model(self, model: str) -> None: ...
    def ai_configured(self) -> bool: ...
    def set_api_key(self, candidate: str) -> bool: ...
    def remove_api_key(self) -> bool: ...
    def test_ai(self) -> bool: ...
    def answer(self, question: str): ...
    def source_details(self, message_ids: tuple[int, ...], source_refs: tuple[str, ...]) -> list[dict]: ...
    def health(self) -> dict: ...
    def stats(self) -> dict: ...
    def clear_cache(self) -> int: ...
    def reindex(self): ...
